
spring:
  application:
    name: BAND-USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/newdick?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7000
